In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('/data/complications.csv')

In [3]:
data['city'].value_counts()

BIRMINGHAM        76
MOBILE            38
GADSDEN           38
ANNISTON          38
DOTHAN            38
MONTGOMERY        38
TALLADEGA         19
FLORENCE          19
FORT PAYNE        19
BREWTON           19
CULLMAN           19
HUNTSVILLE        19
SCOTTSBORO        19
DADEVILLE         19
SHEFFIELD         19
WINFIELD          19
ALABASTER         19
EUFAULA           19
EUTAW             19
ALEXANDER CITY    19
OPELIKA           19
ENTERPRISE        19
OPP               19
TUSCALOOSA        19
ANDALUSIA         19
JASPER            19
GREENSBORO        19
CENTRE            19
BOAZ              19
GROVE HILL        19
FAIRHOPE          19
WETUMPKA          19
DECATUR           19
GENEVA            19
FOLEY             19
HAMILTON          19
MOULTON           19
TALLASSEE         19
CENTREVILLE       19
LUVERNE           19
ASHLAND           19
OZARK             19
FAYETTE           19
ATHENS            19
CAMDEN            12
Name: city, dtype: int64

In [5]:
birmingham = data['city'] == 'BIRMINGHAM'

In [7]:
data_b = data[birmingham]

In [8]:
data_b['state'].unique()

array(['AL'], dtype=object)

In [11]:
data['state'].value_counts()

AL    1000
Name: state, dtype: int64

In [12]:
data.head()

,provider_id,hospital_name,address,city,state,zip_code,county_name,phone_number,measure_id,measure_name,compared_to_national,denominator,score,lower_estimate,higher_estimate,footnote,measure_start_date,measure_end_date
0,10001,SOUTHEAST ALABAMA MEDICAL CENTER,1108 ROSS CLARK CIRCLE,DOTHAN,AL,36301,HOUSTON,(334) 793-8701,COMP_HIP_KNEE,Rate of complications for hip/knee replacement...,No Different Than the National Rate,292,3.2,2.1,4.8,NaN,2015-04-01T00:00:00.000,2018-03-31T00:00:00.000
1,10001,SOUTHEAST ALABAMA MEDICAL CENTER,1108 ROSS CLARK CIRCLE,DOTHAN,AL,36301,HOUSTON,(334) 793-8701,MORT_30_AMI,Death rate for heart attack patients,No Different Than the National Rate,688,13,11.0,15.5,NaN,2015-07-01T00:00:00.000,2018-06-30T00:00:00.000
2,10001,SOUTHEAST ALABAMA MEDICAL CENTER,1108 ROSS CLARK CIRCLE,DOTHAN,AL,36301,HOUSTON,(334) 793-8701,MORT_30_CABG,Death rate for CABG surgery patients,No Different Than the National Rate,291,4.3,2.6,6.8,NaN,2015-07-01T00:00:00.000,2018-06-30T00:00:00.000
3,10001,SOUTHEAST ALABAMA MEDICAL CENTER,1108 ROSS CLARK CIRCLE,DOTHAN,AL,36301,HOUSTON,(334) 793-8701,MORT_30_COPD,Death rate for COPD patients,No Different Than the National Rate,411,8.8,6.7,11.4,NaN,2015-07-01T00:00:00.000,2018-06-30T00:00:00.000
4,10001,SOUTHEAST ALABAMA MEDICAL CENTER,1108 ROSS CLARK CIRCLE,DOTHAN,AL,36301,HOUSTON,(334) 793-8701,MORT_30_HF,Death rate for heart failure patients,No Different Than the National Rate,869,12.7,10.7,15.0,NaN,2015-07-01T00:00:00.000,2018-06-30T00:00:00.000

In [16]:
not_available = data['score'] == 'Not Available'

In [17]:
data_b = data[birmingham & ~not_available]

In [18]:
len(data_b)

66

In [19]:
above10 = data_b['score'].astype(float) >= 10

In [20]:
data_b[above10]

,provider_id,hospital_name,address,city,state,zip_code,county_name,phone_number,measure_id,measure_name,compared_to_national,denominator,score,lower_estimate,higher_estimate,footnote,measure_start_date,measure_end_date
96,10011,ST VINCENT'S EAST,50 MEDICAL PARK EAST DRIVE,BIRMINGHAM,AL,35235,JEFFERSON,(205) 838-3122,MORT_30_AMI,Death rate for heart attack patients,No Different Than the National Rate,170,14.8,11.7,18.4,NaN,2015-07-01T00:00:00.000,2018-06-30T00:00:00.000
98,10011,ST VINCENT'S EAST,50 MEDICAL PARK EAST DRIVE,BIRMINGHAM,AL,35235,JEFFERSON,(205) 838-3122,MORT_30_COPD,Death rate for COPD patients,No Different Than the National Rate,257,10.5,8.0,13.6,NaN,2015-07-01T00:00:00.000,2018-06-30T00:00:00.000
99,10011,ST VINCENT'S EAST,50 MEDICAL PARK EAST DRIVE,BIRMINGHAM,AL,35235,JEFFERSON,(205) 838-3122,MORT_30_HF,Death rate for heart failure patients,No Different Than the National Rate,400,11.3,9.0,13.8,NaN,2015-07-01T00:00:00.000,2018-06-30T00:00:00.000
100,10011,ST VINCENT'S EAST,50 MEDICAL PARK EAST DRIVE,BIRMINGHAM,AL,35235,JEFFERSON,(205) 838-3122,MORT_30_PN,Death rate for pneumonia patients,No Different Than the National Rate,424,17.4,14.4,20.4,NaN,2015-07-01T00:00:00.000,2018-06-30T00:00:00.000
101,10011,ST VINCENT'S EAST,50 MEDICAL PARK EAST DRIVE,BIRMINGHAM,AL,35235,JEFFERSON,(205) 838-3122,MORT_30_STK,Death rate for stroke patients,No Different Than the National Rate,153,12.7,9.6,16.4,NaN,2015-07-01T00:00:00.000,2018-06-30T00:00:00.000
103,10011,ST VINCENT'S EAST,50 MEDICAL PARK EAST DRIVE,BIRMINGHAM,AL,35235,JEFFERSON,(205) 838-3122,PSI_11_POST_RESP,Postoperative Respiratory Failure Rate,Worse Than the National Rate,584,13.79,8.42,19.16,NaN,2016-07-01T00:00:00.000,2018-06-30T00:00:00.000
109,10011,ST VINCENT'S EAST,50 MEDICAL PARK EAST DRIVE,BIRMINGHAM,AL,35235,JEFFERSON,(205) 838-3122,PSI_4_SURG_COMP,Deaths among Patients with Serious Treatable C...,No Different Than the National Rate,83,164.15,122.42,205.88,NaN,2016-07-01T00:00:00.000,2018-06-30T00:00:00.000
286,10033,UNIVERSITY OF ALABAMA HOSPITAL,619 SOUTH 19TH STREET,BIRMINGHAM,AL,35233,JEFFERSON,(205) 934-4011,MORT_30_AMI,Death rate for heart attack patients,No Different Than the National Rate,325,13,10.6,15.7,NaN,2015-07-01T00:00:00.000,2018-06-30T00:00:00.000
290,10033,UNIVERSITY OF ALABAMA HOSPITAL,619 SOUTH 19TH STREET,BIRMINGHAM,AL,35233,JEFFERSON,(205) 934-4011,MORT_30_PN,Death rate for pneumonia patients,Better Than the National Rate,612,11.4,9.6,13.8,NaN,2015-07-01T00:00:00.000,2018-06-30T00:00:00.000
291,10033,UNIVERSITY OF ALABAMA HOSPITAL,619 SOUTH 19TH STREET,BIRMINGHAM,AL,35233,JEFFERSON,(205) 934-4011,MORT_30_STK,Death rate for stroke patients,No Different Than the National Rate,502,15.3,12.8,18.1,NaN,2015-07-01T00:00:00.000,2018-06-30T00:00:00.000
299,10033,UNIVERSITY OF ALABAMA HOSPITAL,619 SOUTH 19TH STREET,BIRMINGHAM,AL,35233,JEFFERSON,(205) 934-4011,PSI_4_SURG_COMP,Deaths among Patients with Serious Treatable C...,No Different Than the National Rate,643,178.14,156.53,199.76,NaN,2016-07-01T00:00:00.000,2018-06-30T00:00:00.000
552,10056,ST VINCENT'S BIRMINGHAM,810 ST VINCENT'S DRIVE,BIRMINGHAM,AL,35205,JEFFERSON,(205) 939-7000,MORT_30_AMI,Death rate for heart attack patients,No Different Than the National Rate,213,13.5,10.8,16.7,NaN,2015-07-01T00:00:00.000,2018-06-30T00:00:00.000
556,10056,ST VINCENT'S BIRMINGHAM,810 ST VINCENT'S DRIVE,BIRMINGHAM,AL,35205,JEFFERSON,(205) 939-7000,MORT_30_PN,Death rate for pneumonia patients,No Different Than the National Rate,621,14.4,12.2,16.8,NaN,2015-07-01T00:00:00.000,2018-06-30T00:00:00.000
557,10056,ST VINCENT'S BIRMINGHAM,810 ST VINCENT'S DRIVE,BIRMINGHAM,AL,35205,JEFFERSON,(205) 939-7000,MORT_30_STK,Death rate for stroke patients,No Different Than the National Rate,374,14,11.4,17.1,NaN,2015-07-01T00:00:00.000,2018-06-30T00:00:00.000
565,10056,ST VINCENT'S BIRMINGHAM,810 ST VINCENT'S DRIVE,BIRMINGHAM,AL,35205,JEFFERSON,(205) 939-7000,PSI_4_SURG_COMP,Deaths among Patients with Serious Treatable C...,No Different Than the National Rate,153,161.36,123.41,199.31,NaN,2016-07-01T00:00:00.000,2018-06-30T00:00:00.000

# RegEx Filtering

In [21]:
med_center_filter = data['hospital_name'].str.contains('CENTER$')
med_centers = data[med_center_filter]

In [22]:
med_centers.shape

(456, 18)

In [23]:
med_centers['hospital_name'].value_counts()

D C H REGIONAL MEDICAL CENTER                 19
RIVERVIEW REGIONAL MEDICAL CENTER             19
SHELBY BAPTIST MEDICAL CENTER                 19
NORTH ALABAMA MEDICAL CENTER                  19
RUSSELL MEDICAL CENTER                        19
HIGHLANDS MEDICAL CENTER                      19
NORTHEAST ALABAMA REGIONAL MEDICAL CENTER     19
NORTHWEST MEDICAL CENTER                      19
GADSDEN REGIONAL MEDICAL CENTER               19
SOUTHEAST ALABAMA MEDICAL CENTER              19
WALKER BAPTIST MEDICAL CENTER                 19
DALE MEDICAL CENTER                           19
FLOYD CHEROKEE MEDICAL CENTER                 19
EAST ALABAMA MEDICAL CENTER                   19
SOUTH BALDWIN REGIONAL MEDICAL CENTER         19
CULLMAN REGIONAL MEDICAL CENTER               19
BIBB MEDICAL CENTER                           19
WIREGRASS MEDICAL CENTER                      19
MARION REGIONAL MEDICAL CENTER                19
CITIZENS BAPTIST MEDICAL CENTER               19
LAWRENCE MEDICAL CENTER                       19
DEKALB REGIONAL MEDICAL CENTER                19
FAYETTE MEDICAL CENTER                        19
UNIVERSITY OF SOUTH ALABAMA MEDICAL CENTER    19
Name: hospital_name, dtype: int64

In [25]:
hospital_filter = data['hospital_name'].str.contains('HOSPITAL')
hospitals = data[hospital_filter]

In [26]:
hospitals.shape

(411, 18)

In [ ]:
hospitals['hospital_name'].value_counts()

In [27]:
unknown = data[~hospital_filter & ~med_center_filter]

In [28]:
unknown['hospital_name'].unique()

array(['MARSHALL MEDICAL CENTERS SOUTH CAMPUS', "ST VINCENT'S EAST",
       'BAPTIST MEDICAL CENTER SOUTH', 'ANDALUSIA HEALTH',
       'MEDICAL CENTER ENTERPRISE', "ST VINCENT'S BIRMINGHAM",
       'MEDICAL CENTER BARBOUR'], dtype=object)

In [29]:
data[~(hospital_filter | med_center_filter)]['hospital_name'].unique()

array(['MARSHALL MEDICAL CENTERS SOUTH CAMPUS', "ST VINCENT'S EAST",
       'BAPTIST MEDICAL CENTER SOUTH', 'ANDALUSIA HEALTH',
       'MEDICAL CENTER ENTERPRISE', "ST VINCENT'S BIRMINGHAM",
       'MEDICAL CENTER BARBOUR'], dtype=object)